<?php
require_once dirname(__DIR__) . '/admin/config.php';
require_once dirname(__DIR__) . '/admin/includes/auth.php';
require_once dirname(__DIR__) . '/admin/includes/db.php';
require_once dirname(__DIR__) . '/admin/includes/functions.php';
require_once dirname(__DIR__) . '/admin/includes/layout.php';
hc_require_auth();

// Maps an old, broken page_path (as generated by the pre-fix hc_scan_pages())
// to the correct clean-URL path the live site actually uses.
function hc_fixed_path(string $old): ?string {
    if ($old === '/index') return '/';
    if (preg_match('#^/(Marketing|web-design|seo)/([^/]+)$#', $old, $m)) {
        return '/' . $m[2] . '/';
    }
    return null; // not an old-style broken path, leave alone
}

$run = ($_GET['run'] ?? '') === '1';
$report = ['hc_seo_pages' => [], 'hc_hreflang' => [], 'hc_page_schema' => []];

// hc_seo_pages: page_path is unique, so if the correct path already has a
// row, the broken-path row is orphaned data that never applied — drop it.
// Otherwise, just rename it to the correct path.
foreach (hc_all("SELECT id, page_path FROM hc_seo_pages") as $row) {
    $fixed = hc_fixed_path($row['page_path']);
    if ($fixed === null) continue;
    $clash = hc_val("SELECT id FROM hc_seo_pages WHERE page_path = ?", [$fixed]);
    if ($clash) {
        $report['hc_seo_pages'][] = "DROP orphaned '{$row['page_path']}' (a correct row for '$fixed' already exists)";
        if ($run) hc_q("DELETE FROM hc_seo_pages WHERE id = ?", [$row['id']]);
    } else {
        $report['hc_seo_pages'][] = "RENAME '{$row['page_path']}' -> '$fixed'";
        if ($run) hc_q("UPDATE hc_seo_pages SET page_path = ? WHERE id = ?", [$fixed, $row['id']]);
    }
}

// hc_hreflang: unique per (page_path, locale)
foreach (hc_all("SELECT id, page_path, locale FROM hc_hreflang") as $row) {
    $fixed = hc_fixed_path($row['page_path']);
    if ($fixed === null) continue;
    $clash = hc_val("SELECT id FROM hc_hreflang WHERE page_path = ? AND locale = ?", [$fixed, $row['locale']]);
    if ($clash) {
        $report['hc_hreflang'][] = "DROP orphaned '{$row['page_path']}' [{$row['locale']}] (a correct row already exists)";
        if ($run) hc_q("DELETE FROM hc_hreflang WHERE id = ?", [$row['id']]);
    } else {
        $report['hc_hreflang'][] = "RENAME '{$row['page_path']}' [{$row['locale']}] -> '$fixed'";
        if ($run) hc_q("UPDATE hc_hreflang SET page_path = ? WHERE id = ?", [$fixed, $row['id']]);
    }
}

// hc_page_schema: page_path is NOT unique (a page can have multiple schema
// blocks), so renaming can't clash — just update every matching row.
foreach (hc_all("SELECT id, page_path FROM hc_page_schema") as $row) {
    $fixed = hc_fixed_path($row['page_path']);
    if ($fixed === null) continue;
    $report['hc_page_schema'][] = "RENAME '{$row['page_path']}' -> '$fixed'";
    if ($run) hc_q("UPDATE hc_page_schema SET page_path = ? WHERE id = ?", [$fixed, $row['id']]);
}

$total = count($report['hc_seo_pages']) + count($report['hc_hreflang']) + count($report['hc_page_schema']);

hc_head('Fix Page Paths');
hc_topbar('Fix Page Paths', '<a href="/admin/">Admin</a> › Fix Page Paths');
?>
<div class="page-content">
  <div class="card">
    <div class="card-header">
      <div class="card-title"><?= $run ? 'Migration Applied' : 'Migration Preview' ?></div>
      <div class="card-sub">Realigns SEO pages, hreflang, and schema entries that were saved under the old broken admin page paths (e.g. <code>/Marketing/foo</code>) so they match the real live URL (<code>/foo/</code>).</div>
    </div>
    <?php if ($total === 0): ?>
      <div class="alert alert-info">Nothing to fix — no entries found under the old broken path pattern.</div>
    <?php else: ?>
      <?php foreach ($report as $table => $lines): if (!$lines) continue; ?>
        <h4 style="margin:20px 0 8px"><?= h($table) ?> (<?= count($lines) ?>)</h4>
        <ul style="font-family:monospace;font-size:13px;line-height:1.8">
          <?php foreach ($lines as $l): ?><li><?= h($l) ?></li><?php endforeach; ?>
        </ul>
      <?php endforeach; ?>
      <?php if (!$run): ?>
        <p style="margin-top:20px"><a href="?run=1" class="btn btn-primary" onclick="return confirm('Apply these <?= $total ?> changes now?')">Apply These <?= $total ?> Changes</a></p>
      <?php else: ?>
        <div class="alert alert-success" style="margin-top:20px">Done — applied <?= $total ?> change<?= $total === 1 ? '' : 's' ?>. Delete this file when you're satisfied it worked correctly.</div>
      <?php endif; ?>
    <?php endif; ?>
  </div>
</div>
<?php hc_foot(); ?>
